[tool.poetry]
name           = 'zfit-stubs'
description    = 'Project with stub files for zfit'
version        = '0.0.0'
readme         = 'README.md'
package-mode   = true 
packages       = [
{include='zfit', from='src'}]
classifiers    = [
    "Typing :: Typed",
]

[build-system]
requires      = [
    'poetry-core>=1.0.0',
    'poetry-dynamic-versioning>=1.0.0'
]
build-backend = 'poetry_dynamic_versioning.backend'

[tool.poetry-dynamic-versioning]
enable       = true
vcs          = 'git'
style        = 'pep440'
pattern      = 'default-unprefixed'
format-jinja = """
{%- if distance == 0 -%}
{{ base }}
{%- else -%}
{{ serialize_pep440(bump_version(base), dev=distance) }}
{%- endif -%}
"""
